# Install files

## Configuration file
install(FILES ${PROJECT_BINARY_DIR}/${PROJECT_NAME}Config.h DESTINATION include)

## Docs files
install(FILES ${PROJECT_SOURCE_DIR}/README.md DESTINATION ${PROJECT_NAME}_DATADIR/${PROJECT_NAME})
install(FILES ${PROJECT_SOURCE_DIR}/CODE_OF_CONDUCT.md DESTINATION ${PROJECT_NAME}_DATADIR/${PROJECT_NAME})
install(FILES ${PROJECT_SOURCE_DIR}/LICENSE DESTINATION ${PROJECT_NAME}_DATADIR/${PROJECT_NAME})
install(FILES ${PROJECT_SOURCE_DIR}/PULL_REQUEST_TEMPLATE.md DESTINATION ${PROJECT_NAME}_DATADIR/${PROJECT_NAME})

install(
	FILES ${PROJECT_BINARY_DIR}/${PROJECT_NAME}.desktop 
	DESTINATION ${PROJECT_NAME}_DATADIR/${PROJECT_NAME}/application
)

install(
	FILES project.glade 
	DESTINATION ${PROJECT_NAME}_DATADIR/${PROJECT_NAME}
)
install(
	FILES ${PROJECT_BINARY_DIR}/${PROJECT_NAME}.pc
	DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig
)